In [9]:
import numpy as np

In [2]:
b=np.array([3,4])
b

array([3, 4])

In [3]:
x=np.array([[51,55],[14,19],[0,4]])
x

array([[51, 55],
       [14, 19],
       [ 0,  4]])

In [4]:
type(x[0])

numpy.ndarray

In [5]:
x[0]

array([51, 55])

In [6]:
x[np.array([1,2])]

array([[14, 19],
       [ 0,  4]])

In [7]:
x[x>10]

array([51, 55, 14, 19])

In [11]:
A=np.array([1,2,3,4])
A

array([1, 2, 3, 4])

In [12]:
np.ndim(A)

1

In [15]:
type(A.shape)

tuple

In [14]:
A.shape[0]

4

In [20]:
B=np.array([[1,2],[3,4],[5,6]])
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
A=np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [24]:
B=np.array([[5,6],[7,8]])

In [23]:
B

array([[5, 6],
       [7, 8]])

In [25]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [26]:
X=np.array([1,2])
X

array([1, 2])

In [27]:
W=np.array([[1,3,5],[2,4,6]])
W

array([[1, 3, 5],
       [2, 4, 6]])

In [28]:
np.dot(X,W)

array([ 5, 11, 17])

In [29]:
E=np.array([[1,2],[1,3],[1,4]])
np.shape(E)

(3, 2)

In [30]:
F=np.array(([[1,1,1],[1,2,1],[1,1,2],[2,1,1]]))
np.shape(F)

(4, 3)

In [32]:
np.dot(F,E)

array([[ 3,  9],
       [ 4, 12],
       [ 4, 13],
       [ 4, 11]])

In [33]:
F

array([[1, 1, 1],
       [1, 2, 1],
       [1, 1, 2],
       [2, 1, 1]])

In [34]:
np.uint8(F)

array([[1, 1, 1],
       [1, 2, 1],
       [1, 1, 2],
       [2, 1, 1]], dtype=uint8)